<?php

namespace GroupBundle\Repository;

/**
 * GroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupsRepository extends \Doctrine\ORM\EntityRepository
{
    public function  FindGroupFond($id){
        $qb=$this->getEntityManager()
            ->createQuery("select g from GroupBundle:Groups g where g.idF=?1 ")
            ->setParameters(array(1=>$id));
        return $qb->getResult();
    }




}
