<?php

namespace GroupBundle\Repository;

/**
 * MembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreRepository extends \Doctrine\ORM\EntityRepository
{

    public function  FindGroupFond($id){
        $qb=$this->getEntityManager()
            ->createQuery("select * from GroupBundle:Groups g where g.idF=?1 ")
            ->setParameters(array(1=>$id));
        return $qb->getResult();
    }


    public function  FindGroupMember($id){
        //var_dump($id);
        $qb=$this->getEntityManager()
            //SELECT groups.* FROM groups JOIN membre ON groups.id=membre.idG AND membre.idM=3
            ->createQuery("select g.id,g.nom,g.description from GroupBundle:Groups g join GroupBundle:Membre m where m.idG=g.id and m.idM=".$id);
           // ->setParameters(array(1=>$id));
      //  var_dump($qb);
        return $qb->getResult();
    }
}
