<?php

namespace GroupBundle\Repository;

/**
 * ChatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

    public function  FindChatG($idG){
        $qb=$this->getEntityManager()
            ->createQuery("select g from GroupBundle:Chat g where g.idG=?1 ")
            ->setParameters(array(1=>$idG));
        return $qb->getResult();
    }
}
