<?php

namespace GroupBundle\Repository;

/**
 * ChatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

    public function  FindPostG($idG){
        $qb=$this->getEntityManager()
            ->createQuery("select g from GroupBundle:Post g where g.idG=?1 order By g.id DESC  ")
            ->setParameters(array(1=>$idG));
        return $qb->getResult();
    }


    public function AddLike($id){
        $qb = $this->getEntityManager()->createQuery("update GroupBundle:Post p set p.nbLike =p.nbLike+1 where p.id=?1 ")
            ->setParameters(array(1=>$id));
        return $qb->getResult();
    }


    public function UnLike($id){
        $qb = $this->getEntityManager()->createQuery("update GroupBundle:Post p set p.nbLike =p.nbLike-1 where p.id=?1 ")
            ->setParameters(array(1=>$id));
        return $qb->getResult();
    }

}
